jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  # node's configure script doesn't support python 3
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x' 
      addToPath: true 
      architecture: 'x64'
  # Currently, WebKit compilation requires gperf, so we currently host it in our own "Library"
  - task: DownloadSecureFile@1
    inputs:
      secureFile: gperf.exe
    displayName: 'Download gperf'
  # Note that DownloadSecureFile downloadeds gperf.exe to %AGENT_TEMPDIRECTORY%
  # so we need to add it to the search path in order for WebKit's cmake scripts 
  # to find it.
  - script: |
      set "PATH=%PATH%;%AGENT_TEMPDIRECTORY%" && vcbuild.bat vs2017 x64 nosnapshot noetw noperfctr jsc
    displayName: 'Build node-jsc'
  - script: |
      python deps/jscshim/test/tools/run-tests.py --outdir=..\..\..\Release
    displayName: 'Run jscshim tests'

# - job: iOS
#   pool:
#     vmImage: 'macOS-10.13'
#   steps:
#   - script: |
#       sudo ./deps/jscshim/webkit/Tools/Scripts/configure-xcode-for-ios-development
#       chmod +x ./build_ios.sh
#     workingDirectory: $(Build.SourcesDirectory)
#     displayName: 'Prepare'
#   - script: ./build_ios.sh
#     workingDirectory: $(Build.SourcesDirectory)
#     displayName: 'Build node-jsc'